{% set name = "exchangelib" %}
{% set version = "3.2.0" %}
{% set sha256 = "aef6066f7ea2ba7c8afbbb910c198a7f68f0ffb914734310100b2583d026b427" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - cached-property
    - defusedxml >=0.6.0
    - dnspython >=1.14.0
    - isodate
    - lxml >3.0
    - oauthlib
    - pygments
    - python
    - python-dateutil
    - pytz
    - requests >=2.7
    - requests_ntlm >=0.2.0
    - requests-kerberos
    - requests-negotiate-sspi  # [win]
    - requests-oauthlib
    - tzlocal

test:
  imports:
    - exchangelib

about:
  home: https://github.com/ecederstrand/exchangelib
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Client for Microsoft Exchange Web Services (EWS)
  doc_url: https://github.com/ecederstrand/exchangelib
  dev_url: https://github.com/ecederstrand/exchangelib

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
